language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

addons:
  apt:
    sources:
      - sourceline: deb https://packages.erlang-solutions.com/ubuntu trusty contrib
        key_url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
      - sourceline: deb https://dl.bintray.com/rabbitmq/debian trusty main
        key_url: https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc
    packages:
      - esl-erlang=1:20.1

before_install:
 - sudo mv /opt/jdk_switcher/jdk_switcher.sh /tmp
 - sudo apt-get install rabbitmq-server=3.7.4-1
 - sudo mv /tmp/jdk_switcher.sh /opt/jdk_switcher/
 - sudo rabbitmq-plugins enable rabbitmq_management
 - sudo rabbitmqctl add_user test test
 - sudo rabbitmqctl set_user_tags test administrator
 - sudo rabbitmqctl set_permissions -p / test \".*\" \".*\" \".*\"
 - sudo rabbitmq-plugins enable rabbitmq_shovel
 - chmod +x tests/test_pyrabbit.py
 
install:
  - if [[ $TRAVIS_PYTHON_VERSION != '2.7' ]]; then pip install -r requirements3.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install -r requirements.txt; fi
  - cd tests
script: 
  - if [[ $TRAVIS_PYTHON_VERSION != '2.7' ]]; then python3 test_pyrabbit.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then python test_pyrabbit.py; fi
